### ISSUE TITLE
Display wont' boot

### ISSUE THREAD

**Issue by robhicks** [KayIO/MKSTFT-FLSunQQ#1]
I tried installing following the instructions. I had previously installed the 1.1.9 branch from your https://github.com/KayIO/Marlin-FLSunQQ-Delta repo. 

Now, the display just cycles through rebooting and it will not attempt to read the SD card again.

**Comment by KayIO** [comment]
Hello Rob ! Just download the file 
TFT Firmware 3.0 Moded Original.zip Link: 
https://github.com/KayIO/MKSTFT-FLSunQQ/blob/Original/TFT%20Firmware%203.0%20Moded%20Original.zip
unzip the file and put the content on th SD.
It seems that sometimes the files are downloaded in ASCII code even if they are binaries. That depends to the internet browser and system you are using for downloading.
Even if the display is cycling, which means it's not dead, it will write the new FW again. 
BTW: I already deleted the firmware files 3 months ago. Where did you get them ?

**Comment by robhicks** [comment]
I got them from this here: https://github.com/KayIO/MKSTFT-FLSunQQ/releases

**Comment by KayIO** [comment]
Hm ! Interesting, because this is the right version and should work. It worked for me and a lot of people. We had no reason until now ... Only if you would have downloaded from the source page, there were some issues. That was the reason to delete it.
But the release should also work for you :(

**Comment by robhicks** [comment]
Does it needs the 1.1.9 firmware from your other repo to work? I've tried a number of things to try to load my old firmware. The TFT still recycles through rebooting.

**Comment by KayIO** [comment]
No it does not need it. They are two total different firmwares, which are communicating through the serial interface. Mine 1.1.9 has some special GCODE functions which are also set in the config file for the other TFT firmware. The firmware is the original FLSun TFT firmware, only some lines of the config file changed... Especially for setting delta height. Nothing very special. 
The Marlin FW 1.1.9 can only be updated by USB and the Arduino Interface...
The TFT MKS Firmware can only be updated via the SD Card...

**Comment by robhicks** [comment]
I got my tft unbricked finally. Thanks for your help. Are you using your marlin configuration? If so, is it working well for you?
